### ISSUE TITLE
Sonic Generations Mods and Codes aren't working as intended

### ISSUE THREAD

**Issue by PlatinumPlatedPizza** [thesupersonic16/HedgeModManager#174] opened 2021-01-31 22:40 UTC
never done somethin' like this before

Hello there, developers of the HedgeModManager... sorry to disturb you over this but I require assistance....
you see.... I have a PC with an Intel i7, GeForce RTX 2070 Super, and 16gigs of good old ram...
I have the game located in my second drive
![image](https://user-images.githubusercontent.com/56237812/106399779-626bfb00-63e0-11eb-99cc-d4ff4419f4b5.png)
(My Dick is the name of the second drive because "D:")
all the mods are located there too.... the problem is... some mods don't work entirely... and I'm here to shed some examples

1. Better FxPipeline 
when enabled the mod just gets rid of the HUD entirely....
![image](https://user-images.githubusercontent.com/56237812/106399830-bb3b9380-63e0-11eb-96d0-533f65bf60f4.png)
and it doesn't deliver the promised effects... no matter what other mods I use... like doctective's Shadows Only... I even attempted to use the SonicGML and that didn't work... Better FxPipeline just doesn't want to work... (the one in codes doesn't work either)

Goalringmod27's Custom Jumpball Pack v1.0
![image](https://user-images.githubusercontent.com/56237812/106399965-546aaa00-63e1-11eb-8657-613f5073a8ea.png)
I had to use a separate character mod instead of the custom jumpball this thing promises... I followed the directions in the notepad it provided and even tinkered around in the mod loader and files... still nothing... I had to use separate mods for it to work....

3. Codes

----these are codes I tested myself (no other mod was active)----
All Rings Can Be Light Dashed - Boost Aura Distorted/a chance to crash on startup
![image](https://user-images.githubusercontent.com/56237812/106400070-e2df2b80-63e1-11eb-8572-b8e9ea0e7435.png)
Unleashed Sweepkick - Unable to Light Dash any "Light Dashable Rings"

Longer Blue Trail - No Such Thing (even when using SonicGML)
Stomp Keeps Horizontal Velocity - Crashes on Startup
and... 

Mods like the Unleashed Project and Sonic Unleashed Style, Unleashed Mod, and some Motion Blur Mods like 
![image](https://user-images.githubusercontent.com/56237812/106400178-8c262180-63e2-11eb-8d64-274cddef7439.png)
work wonderfully.... I have no idea where to ask for help.... and there was a public discord somewhere but I cannot seem to find it... 

you certainly have a lot of time on your hands developers.... but if you find the time... maybe you can help me?

Skidoosh my fellow gamers!!!!

**Comment by thesupersonic16** [comment] 2021-02-01 02:02
Can you create and send a snapshot of your configuration here? Just press Shift + F1 on HedgeModManager to create one.

**Comment by PlatinumPlatedPizza** [comment] 2021-02-01 02:59
alright then 
[HMM_Snapshot_00012021205839.txt](https://github.com/thesupersonic16/HedgeModManager/files/5901612/HMM_Snapshot_00012021205839.txt)

**Comment by thesupersonic16** [comment] 2021-02-01 03:47
It seems your copy of Sonic Generations is either broken or its a pirated copy. Please verify the game's content using Steam. There are guides out on the Internet on how to do that. I'm going to close the issue, If the issue still occurs, please reply to this issue.

**Closed as completed by thesupersonic16** 2021-02-01 03:47 UTC

**Comment by PlatinumPlatedPizza** [comment] 2021-02-02 04:42
Yes, the copy within my possession is pirated and if that's really the issue than I understand
I'm not pirating the game because I wanna play it without paying Sega in fact I payed for it on my Xbox 360 and I contacted Microsoft (which was really dumb) If I could somehow get a refund or exchange licenses to the game (since I didn't have a strong computer and didn't think I was getting one at that time) 

![image](https://user-images.githubusercontent.com/56237812/106553017-199a6c00-64de-11eb-8c34-66ad8b53a85a.png)

I really wanted to play Generations with graphical improvements and modifications 

if the piracy code really interferes with the coding of the modding software than I understand
but if it's just because it's a pirated copy then I also understand, I'm not trying to mope to you... it's been really hard these last few days...

sorry about that, mate, I'm really sorry

(this cat here doesn't condone piracy but in this circumstances I really wanted to experience the game just like everyone else)

(also... if you need more evidence... I still have my 360... I can turn it on and show you my download history...)

**Comment by thesupersonic16** [comment] 2021-02-02 04:47
Having evidence isn't going to help. The issue is actually due to how old the cracks are. HedgeModManager only works with the newest build of Sonic Generations. So the issue is completely out of our control unless we actively support the older builds which we don't want.
