### ISSUE TITLE
Hedgemodmanager Isuue

### ISSUE THREAD

**Issue by SonicFanboy2007** [thesupersonic16/HedgeModManager#252] opened 2021-06-11 18:50 UTC
HMM Info:
```
    Version: 7.4-2
    Args: 
    StartDir: D:\Steam\steamapps\common\Sonic Generations\
    Process Level: Administrator
    Game: Unnamed Game
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.Collections.Generic.List`1[HedgeModManager.SteamGame] SearchForGames(System.String)
    StackTrace: 
       at HedgeModManager.Steam.SearchForGames(String preference)
       at HedgeModManager.HedgeApp.Main(String[] args)
    InnerException: 
```

**Comment by thesupersonic16** [comment] 2021-06-11 18:55
Duplicate of #251 Please update HedgeModManager to 7.4-3 as this fixes this issue.

Reopen this issue if issue persists after updating.

**Closed as completed by thesupersonic16** 2021-06-11 18:55 UTC
