### ISSUE TITLE
Sonic Forces mods not loading

### ISSUE THREAD

**Issue by DreamTeamdidnothingwrong** [thesupersonic16/HedgeModManager#365] opened 2021-12-31 20:33 UTC
I tried loading three different mods for Sonic Forces with HMM, and none of them loaded at all, instead launching the base game as normal. I don't have any codes enabled, and I've enabled the mod loader and save file redirection for the Freight Frenzy Mod, as required by the mod. The mod and game directories are correct as well. 
Here are the three mods I tried, if that helps.
https://gamebanana.com/mods/51046
https://gamebanana.com/mods/150179
https://gamebanana.com/mods/51020

I have also tried two different HMM versions, 7.6.2 and 7.5, with both behaving the same and not loading any mods. 

If there's some log I can pull and fix this issue, I'd be very happy to find it. Thanks

**Comment by thesupersonic16** [comment] 2022-01-01 02:44
Can you enable debug console and try running the game with one of the mods and send me what it says at the top when you reach the title screen?

**Comment by DreamTeamdidnothingwrong** [comment] 2022-01-02 06:40
I enabled the debug console, and the text is always "Starting HE2ModLoader v1.0.2" until I close the game. Even though this is probably a basic issue, all I have tried is re-installing the mod loader, and re-checking the game and mod directories.

**Comment by thesupersonic16** [comment] 2022-01-02 06:54
Are you running a pirated copy of Sonic Forces or a legit copy from Steam? This issue is pretty common with pirated copies and I don't know how nor do I feel like supporting those.

**Comment by DreamTeamdidnothingwrong** [comment] 2022-01-02 07:21
Alright, that's understandable. I'll probably buy a real copy then, sorry about the trouble

**Comment by thesupersonic16** [comment] 2022-01-02 07:36
np, I think the issue is that steam emulators are not responding correctly when the ML wants to know what game it is being loaded from.

Anyways closing.

**Closed as completed by thesupersonic16** 2022-01-02 07:36 UTC
