### ISSUE TITLE
[Bug] HMM wont run on steam deck even after downloading correctly

### ISSUE THREAD

**Issue by urboisal** [thesupersonic16/HedgeModManager#598] opened 2023-03-22 19:32 UTC
So I was following a video by Linux Gaming Central about getting Sonic Frontiers mods and I made it all the way to the end. I got HMM installed, but instead of starting up (Which is what it said it was trying to do) I get a Wine error (It said wineserver: using server-side synchronization and wine: RLIMIT_NICE is <= 20, unable to use setpriority safely). After these show up, it then proceeds to dump a bunch of text in the terminal that I don't understand (To be fair I didn't understand anything I was reading but still). I was able to install it but it just won't load for some reason.

**Comment by RagdollClash** [comment] 2023-03-23 02:32
Duplicate of #597, also we have a thread for Linux support at #219.

**Closed as completed by RagdollClash** 2023-03-23 02:32 UTC
Labels: duplicate
