### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#378] opened 2022-03-22 20:43 UTC
I added a code and then HMM crashed

HMM Info:
```
    Version: 7.6-2
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(3,6): error CS0103: The name 'initialized' does not exist in the current context
(13,23): error CS0103: The name '_0' does not exist in the current context
(14,27): error CS0103: The name '_50_60' does not exist in the current context
(23,2): error CS0103: The name 'initialized' does not exist in the current context

    Source: HedgeModManager
    Function: System.Threading.Tasks.Task CompileCodes(System.Collections.Generic.IEnumerable`1[HedgeModManager.Code], System.IO.Stream, System.String[])
    StackTrace: 
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, Stream resultStream, String[] loadPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 79
       at HedgeModManager.CodeProvider.CompileCodes(IEnumerable`1 sources, String assemblyPath, String[] loadsPaths) in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\CodeProvider.cs:line 72
       at HedgeModManager.ModsDB.<SaveDB>d__27.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__38.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 477
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__50.MoveNext() in C:\Users\SuperSonic16\source\repos\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 801
    InnerException: 
```

**Comment by Sajidur78** [comment] 2022-03-22 20:44
Duplicate of #377

**Closed as completed** 2022-03-22 20:44 UTC
