### ISSUE TITLE
[SonicFrontiers] Mod Manager Crashing After Update

### ISSUE THREAD

**Issue by SpeedyFlash05** [thesupersonic16/HedgeModManager#711] opened 2023-09-02 02:22 UTC
I have no idea what changed or what is causing this crash. Yesterday the game was working fine, but today after I updated the Mod Manager it gives an error whenever I click "Save" or "Save and Play"

[HMM_Snapshot_00092023121630.txt](https://github.com/thesupersonic16/HedgeModManager/files/12502622/HMM_Snapshot_00092023121630.txt)

HMM Info:
```
    Version: 7.10-3
    Args: 
    StartDir: E:\SteamLibrary\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: Exception
    Message: Error compiling codes
(403,9): error CS0103: The name 'Resources' does not exist in the current context

    Source: HedgeModManager.CodeCompiler
    Function: System.Threading.Tasks.Task CompileCodes[TCollection](TCollection, System.IO.Stream, HedgeModManager.CodeCompiler.PreProcessor.IIncludeResolver, System.String[])
    StackTrace: 
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 664
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 995
    InnerException: 
```

**Comment by RagdollClash** [comment] 2023-09-02 02:40
Update your community codes.

**Comment by SpeedyFlash05** [comment] 2023-09-02 02:47
> Update your community codes.

I have, it doesn't fix anything

**Comment by RagdollClash** [comment] 2023-09-02 03:53
Can you send a list of codes and mods that you currently have enabled? I'm not able to reproduce it on my end.

**Comment by SpeedyFlash05** [comment] 2023-09-02 04:06
I've tried disabling everything but I still get the same error so I'm not sure it would help much, but here is my list of mods and codes that I normally have enabled:
![image](https://github.com/thesupersonic16/HedgeModManager/assets/83341682/5dfdf21d-f245-4f27-afa8-5de7767ae642)

![image](https://github.com/thesupersonic16/HedgeModManager/assets/83341682/1a195900-818f-4878-8931-281043da2896)

I've also tried reinstalling the Mod Loader

**Comment by Sajidur78** [comment] 2023-09-02 11:01
One of the mods or codes is likely causing issues, try disabling them one by one

**Comment by SpeedyFlash05** [comment] 2023-09-02 13:21
I don't really see how that would be the case since I tried disabling all of them, but I'll try and update you probably tomorrow (Australian time)

**Comment by hyperbx** [comment] 2023-09-02 13:27
Update your codes again, fixed in commit https://github.com/hedge-dev/HMMCodes/commit/51a8ea0a1022ede311a006e95d774028551f36c9.

**Comment by SpeedyFlash05** [comment] 2023-09-02 13:42
Oh cool, it's all good now! Thanks so much!

**Closed as completed** 2023-09-02 13:44 UTC
