### ISSUE TITLE
[SonicGenerations] z

### ISSUE THREAD

**Issue by Sonicsuper123** [thesupersonic16/HedgeModManager#691] opened 2023-08-21 23:10 UTC
HMM Info:
```
    Version: 7.10-2
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations Demo\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: Win32Exception
    Message: The specified executable is not a valid application for this OS platform.
    Source: System
    Function: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
    StackTrace: 
       at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
       at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
       at HedgeModManager.MainWindow.StartGame() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 670
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in F:\Git\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 998
    InnerException: 
```

**Comment by hyperbx** [comment] 2023-08-21 23:11
Duplicate of https://github.com/thesupersonic16/HedgeModManager/issues/690.

**Closed as completed by hyperbx** 2023-08-21 23:11 UTC
