### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ghost** [thesupersonic16/HedgeModManager#163] opened 2021-01-09 03:11 UTC
I updated hedgemod manager and now it disappeared on my desktop. It activated a mod that crashed sonic generations and now i cant play it until i turn off that mod. Speaking of it, i cant use it, it will load to the hub world then it will crash. If i try the 30 sec trial and rank it crashes.

I expected it to just update but it didnt.

I cant find it in my files unless i didnt look hard enough.

**Comment by Sajidur78** [comment] 2021-01-09 16:29
Updating HMM shouldn't make it disappear, you probably haven't looked hard enough. And, what mod is crashing the game? there is little to no detail available.

**Comment by ghost** [comment] 2021-01-09 19:21
Its the tropical resort all in one mod that crashes my game

**Comment by Sajidur78** [comment] 2021-01-09 19:52
What GPU do you have? This is mod issue than a HMM issue.

**Comment by ghost** [comment] 2021-01-09 21:26
My gpu us Intel(R) Core(TM) i7-9750H

**Comment by Sajidur78** [comment] 2021-01-09 22:15
That is your CPU, I meant the graphics card.

**Comment by ghost** [comment] 2021-01-10 20:34
my gpu is nvidia geforce gtx 1660 ti

**Comment by Sajidur78** [comment] 2021-01-10 23:37
Many old mods for generations crash with Nvidia Turing GPUs, including the GTX 1660Ti. Not a HedgeModManager issue.

**Comment by ghost** [comment] 2021-01-11 05:07
is there a way to fix this?

**Comment by ghost** [comment] 2021-01-11 22:50
where would i look to find hmm?

**Comment by thesupersonic16** [comment] 2021-01-11 23:17
HMM is stored wherever you downloaded the exe file. Unless you meant where the mods are, you can find that by pressing "Open Mods Directory" in the Settings tab.

**Comment by ghost** [comment] 2021-01-12 03:50
i left it in downloads and it isnt there

**Comment by Sajidur78** [comment] 2021-01-12 10:02
Just download the latest version from releases, [link](https://github.com/thesupersonic16/HedgeModManager/releases/download/7.2-9/HedgeModManager.exe). The updater has been tested many times and, this sort issue has never came across. Only thing that can cause this is external interference (ex. Antivirus Software). The issue is not related to HMM. Closing.

**Closed as completed by Sajidur78** 2021-01-12 10:02 UTC

**Comment by ghost** [comment] 2021-01-12 16:24
i downloaded it and it works. All my mods are still here.
