### ISSUE TITLE
[Forces] Game lags with manager installed

### ISSUE THREAD

**Issue by EternityEngine** [thesupersonic16/HedgeModManager#32] opened 2018-07-13 02:31 UTC
Hi, my copy of Sonic Forces lags only when HedgeModManager is installed, even when no mods/codes are activated. It's almost entirely on the world map, with a bit when I first enter a level and when the game boots up. Sometimes opening the start menu fixes it for a bit.

I have the game on Steam, and I am running the minimum specs graphics card, but didn't have any lag at all beforehand.

I've attached my log file if that helps.
[HedgeModManager.log](https://github.com/thesupersonic16/HedgeModManager/files/2190997/HedgeModManager.log)

**Comment by thesupersonic16** [comment] 2018-10-20 08:03
Sorry for the late reply, But is the issue still present in FML 6.4?

**Comment by EternityEngine** [comment] 2018-10-23 02:53
Hi, I don't know what FML is but the latest AppVeyor build has fixed the world map lag! I still get some lag when entering a level but that's not a big issue. Thanks!

**Comment by slashiee** [comment] 2018-10-23 03:02
FML is what allows mods to load in forces. the latest FML version is 6.5, so it seems like the issue was fixed in 6.4

gonna wait for ss16 to see this though before closing

**Comment by thesupersonic16** [comment] 2018-10-23 04:33
Cool, Thanks for the replying and checking out the latest build, Sounds like the Issue is solved, Reopen if the issue comes back.

**Closed by thesupersonic16** 2018-10-23 04:33 UTC
