### ISSUE TITLE
[Bug] Hedge Mod Manager crashes whenever trying to use profiles.

### ISSUE THREAD

**Issue by CJBlueThunder** [thesupersonic16/HedgeModManager#735] opened 2023-09-19 21:45 UTC
## Describe the issue/bug

Every time I try to do absolutely anything involving profiles, Hedge Mod Manager crashes.
## Expected Behaviour

I should be able to create, delete, edit, or switch profiles.

**Comment by thesupersonic16** [comment] 2023-10-26 11:51
Please send a snapshot file which is generated when you press `Submit Report on GitHub`.

**Comment by CJBlueThunder** [comment] 2023-12-03 02:11
boo

**Comment by DeaTh-G** [comment] 2023-12-03 12:09
@CJBlueThunder If you are going to keep the issue open then please provide the information requested by @thesupersonic16 as the issue can not be investigated without it, otherwise the issue will be closed due to inactivity and un-cooperative behaviour.

**Comment by CJBlueThunder** [comment] 2023-12-07 20:55
[HMM_Snapshot_00122023155422.txt](https://github.com/thesupersonic16/HedgeModManager/files/13605205/HMM_Snapshot_00122023155422.txt)

**Comment by thesupersonic16** [comment] 2023-12-11 16:32
It appears one or more of mods you have installed has a malformed configuration file/schema.

Can you first try remove the `Frontiers Physics` mod as this crash has been reported in the past caused by that mod.

If HMM still crashes after removing that mod, can you go through all the mods with the lit up gear symbol and see if any of them cause a crash when editing the configuration even with no changes.

**Comment by CJBlueThunder** [comment] 2023-12-12 00:38
It’s not a mod. It’s the settings of HedgeModManager itself.

**Comment by thesupersonic16** [comment] 2023-12-12 05:30
I am going to leave this issue if you are not going to cooperate.

**Comment by CJBlueThunder** [comment] 2023-12-14 01:05
I am cooperating. I've tried to use the profiles with every mod and code turned off, but it always crashes.

**Comment by thesupersonic16** [comment] 2023-12-14 03:14
That is not what I said to do, try removing the mod I mentioned first.

**Comment by CJBlueThunder** [comment] 2023-12-15 09:37
oh shit it actually worked. I thought it wouldn't work since it was happening before I got that mod.

**Comment by CJBlueThunder** [comment] 2023-12-15 09:43
what do I do about the mod though? I want to keep it

**Comment by thesupersonic16** [comment] 2023-12-15 09:44
You will need to report the issue to the mod author.

**Comment by DeaTh-G** [comment] 2023-12-15 11:34
Labeled as a bug because this shouldn't cause a crash on HedgeModManager's side in the future anyway.
@thesupersonic16 will be looking into implementing a fix.

**Comment by thesupersonic16** [comment] 2023-12-15 12:25
Issue should be fixed in 50dbb8c380aeb533286d86a2b072db2c707cb141, reopen if the crash still persists.

**Closed as completed by thesupersonic16** 2023-12-15 12:25 UTC
Labels: bug
