### ISSUE TITLE
[Bug] Development version will not download

### ISSUE THREAD

**Issue by AHMach1000** [thesupersonic16/HedgeModManager#539] opened 2022-12-23 07:09 UTC
I reinstalled HMM and now when I try to switch to the development updates channel, the download window pops up but nothing will download. Updates were working normally within the past couple days.

**Comment by RagdollClash** [comment] 2022-12-23 07:14
This is an issue caused by nightly.link being down, so there's nothing we're able to do about it outside from waiting for it to go back up.

In the meantime, here's the latest developer version from GitHub Actions:
[HedgeModManager-Release.zip](https://github.com/thesupersonic16/HedgeModManager/files/10293163/HedgeModManager-Release.zip)

**Comment by RagdollClash** [comment] 2022-12-24 02:58
Looks like nightly.link is back up. Closing.

**Closed as completed by RagdollClash** 2022-12-24 02:58 UTC
