### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by trulsbros** [thesupersonic16/HedgeModManager#679] opened 2023-08-09 21:33 UTC
HMM Info:
```
    Version: 7.10-1
    Args: 
    StartDir: D:\Steam\steamapps\common\SonicFrontiers
    Process Level: User
    Game: Sonic Frontiers
    GameInstall: Sonic Frontiers
    Update Status: Up To Date
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: System.String Resolve(System.String)
    StackTrace: 
       at HedgeModManager.ModsDB.Resolve(String name) in D:\GitHub\HedgeModManager\HedgeModManager\ModsDB.cs:line 541
       at HedgeModManager.CodeCompiler.PreProcessor.TextProcessor.Process(String text)
       at HedgeModManager.CodeCompiler.SyntaxTreeEx.ProcessText(String text, TextProcessor& preprocessor, IIncludeResolver includeResolver)
       at HedgeModManager.CodeCompiler.SyntaxTreeEx.Parse(String text, IIncludeResolver includeResolver)
       at HedgeModManager.CodeCompiler.CodeProvider.GetLoadAssemblies[TCollection](TCollection sources, IIncludeResolver includeResolver, String[] lookupPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, Stream resultStream, IIncludeResolver includeResolver, String[] loadPaths)
       at HedgeModManager.CodeCompiler.CodeProvider.CompileCodes[TCollection](TCollection sources, String assemblyPath, IIncludeResolver includeResolver, String[] loadsPaths)
       at HedgeModManager.ModsDB.<SaveDB>d__30.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveModsDB>d__42.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 655
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at HedgeModManager.MainWindow.<SaveConfig>d__54.MoveNext() in D:\GitHub\HedgeModManager\HedgeModManager\UI\MainWindow.xaml.cs:line 986
    InnerException: 
```

**Comment by trulsbros** [comment] 2023-08-09 21:34
i am trying to save the mod profile, that pops up. i try to save and play, that pops up again. and the game wont launch at all anymore

**Comment by thesupersonic16** [comment] 2023-08-12 13:29
Sorry for the delay and thanks for reporting, but this is a dupe of another reported issue #678. Can you please move to that issue and provide some additional information.

**Closed as not planned by thesupersonic16** 2023-08-12 13:29 UTC
Labels: duplicate
