### ISSUE TITLE
[Bug] Specific mods wont enable when checked

### ISSUE THREAD

**Issue by TitoTheOG** [thesupersonic16/HedgeModManager#76] opened 2020-03-06 00:26 UTC
So I have been having this issue with a lot of Sonic Generations mods, mainly Raphpowers Unleashingv8, Voice Conversion mods, physics changing, and other mods. Some mods do work though but these mods I have downloaded say they need the HedgeModManager yet they wont work. Here are screenshots of my ModManager
![manager 3](https://user-images.githubusercontent.com/61854236/76038287-da9b1980-5f0e-11ea-8e44-03665a120521.JPG)
![manager 1](https://user-images.githubusercontent.com/61854236/76038288-da9b1980-5f0e-11ea-93a7-8e76182dc311.JPG)
![manager 2](https://user-images.githubusercontent.com/61854236/76038289-db33b000-5f0e-11ea-9da7-4ccd7edd0c80.JPG)

**Comment by thesupersonic16** [comment] 2020-03-06 03:00
For Unleashingv8, It's not a HedgeModManager issue/bug, Its because Raphpower provided a malformed mod.ini which the newest version of CPKREDIR nolonger works with. HMM can sometimes fix this error with some [simple steps](https://github.com/thesupersonic16/HedgeModManager/issues/74#issuecomment-592869317) or you can [fix the file yourself with these steps](https://gamebanana.com/tools/6311?post=8633664).

For the other mods, Do you mind stating all the mods that do not work?

**Comment by TitoTheOG** [comment] 2020-03-06 04:56
There were quite a few, the project 06 Sonic model+ physics, colors sonic model, jason griffeth voice mod that is hedgemanager read, just a few that I noticed. I did try the right click edit mod and ok method and that seemed to fix it. Thanks!

**Comment by thesupersonic16** [comment] 2020-03-06 05:58
Just checked. All the mods you mentioned has a malformed mod.ini besides the 06 mods, those have an invalid IncludeDir, which was used stupidly in the past for whatever reason.

For the 06 mods, if you are doing them manually, just change IncludeDir0 to "."

Anyways since the issue isn't related to HMM, I will be closing this. Thanks for sending a report. May even link this for any duplicates that come in. Feel free to reopen if there are any issues.

**Closed as completed by thesupersonic16** 2020-03-06 05:58 UTC
