### ISSUE TITLE
[Error] Shadow generations crashes on launch

### ISSUE THREAD

**Issue by PeterP-nut** [thesupersonic16/HedgeModManager#976] opened 2024-12-17 16:25 UTC
## Describe the issue/bug

after the update the game crashes on launch 
## Expected Behaviour

if i disable the mod loader the game works normally, its only when i enable the mod loader the game crashes on launch
## Additional Context

it's after the DLC update, playing on epic games

![AU8geSMU7u](https://github.com/user-attachments/assets/1ffaa22c-6e9f-4ef1-8f39-b02a98ce6eaf)

**Comment by thesupersonic16** [comment] 2024-12-17 16:27
Try again with no mods and codes enabled.

**Comment by PeterP-nut** [comment] 2024-12-17 16:33
> Try again with no mods and codes enabled.

it worked when i toggled mods off, and few codes enabled

**Comment by thesupersonic16** [comment] 2024-12-17 16:49
Report the issue to the mod author. It is likely the mod is outdated.

Since it is believed the issue is mod related, I will be closing this issue. Reopen the issue on the appropriate repo if it is believed not to be a mod issue.

**Closed as completed by thesupersonic16** 2024-12-17 16:49 UTC
