### ISSUE TITLE
[SonicFrontiers] 

### ISSUE THREAD

**Issue by anthgood22** [thesupersonic16/HedgeModManager#726] opened 2023-09-16 05:01 UTC
[HMM_Snapshot_00092023010251.txt](https://github.com/thesupersonic16/HedgeModManager/files/12639875/HMM_Snapshot_00092023010251.txt)

**Comment by RagdollClash** [comment] 2023-09-16 05:07
Assuming from #727, duplicate of #724.

**Closed as not planned by RagdollClash** 2023-09-16 05:07 UTC
