### ISSUE TITLE
Mods Not Working (Sonic Forces)

### ISSUE THREAD

**Issue by idk321321** [thesupersonic16/HedgeModManager#391] opened 2022-04-08 22:08 UTC
Hello There, There seems to be a problem that whenever I open the game the mods don't activate and that's the message on the debug Console:[HE2ML] [INFO]  Starting HE2ModLoader v1.0.2...
[HMM_Snapshot_00042022000751.txt](https://github.com/thesupersonic16/HedgeModManager/files/8455528/HMM_Snapshot_00042022000751.txt)
Here's the log file
I have already tried reinstalling and I checked that everything is on
The HedgeModManager works fine on Generations but it is not doing anything in Forces at all
Edit:I found out that after closing the game these messages appear in the debug console
![Screenshot 2022-04-09 015647](https://user-images.githubusercontent.com/103279479/162547855-dc5f6821-a419-4e31-b7dd-98dd47ebd05c.png)
Edit:it is a pirated version but I wanna know if there is a way to bypass I remember mods working in the past

**Comment by MARCpoot1** [comment] 2022-07-21 14:35
have you solved the problem? the same thing is happening to me too

**Comment by thesupersonic16** [comment] 2022-07-21 14:41
The best you can do is downgrade to an old version of ForcesModLoader, Its on the GitHub history, not gonna provide any support for it nor how to install it.
The issue is caused by the cracks overriding the Steam imports which breaks the new game ID check in the ML. This is not intentionally done, and I might provide an override in the next update if one is even needed.

Since this is a pirated version I will be closing this issue.

**Closed as not planned by thesupersonic16** 2022-07-21 14:41 UTC
