### ISSUE TITLE
I Have A Nvidia GTX

### ISSUE THREAD

**Issue by OtakuFan1** [thesupersonic16/HedgeModManager#264] opened 2021-06-30 08:18 UTC
I have Nvidia GTX and did pam000_broke and still the hub world is messed up

**Comment by thesupersonic16** [comment] 2021-07-02 05:44
I unfortunately will have to close this issue as it is irrelevant to HedgeModManager as a project. Unless this is actually caused by a modloader and not an incompatibility of your GPU with a mod, please reopen with additional information.
Otherwise, please send this question to the mod developer or if you are the modder, try asking on GameBanana.

Also GTX 16xx GPUs are also included in the RTX issue.

**Closed as completed by thesupersonic16** 2021-07-02 05:44 UTC
