### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by SanicBoi74** [thesupersonic16/HedgeModManager#242] opened 2021-06-02 04:26 UTC
[HMM_Snapshot_00062021212556.txt](https://github.com/thesupersonic16/HedgeModManager/files/6581971/HMM_Snapshot_00062021212556.txt)
HMM Info:
```
    Version: 7.4-1
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: NullReferenceException
    Message: Object reference not set to an instance of an object.
    Source: HedgeModManager
    Function: Void RefreshProfiles()
    StackTrace: 
       at HedgeModManager.MainWindow.RefreshProfiles()
    InnerException: 
```

**Comment by thesupersonic16** [comment] 2021-06-02 04:29
Thanks for including a snapshot file.
Since this is also a duplicate of #241, make sure to subscribe there so you will be notified about any updates for the issue.

**Closed as completed by thesupersonic16** 2021-06-02 04:29 UTC
