### ISSUE TITLE
[Bug] HMM doesn't want to run on steam deck

### ISSUE THREAD

**Issue by urboisal** [thesupersonic16/HedgeModManager#597] opened 2023-03-22 00:35 UTC
So I was following a video by Linux Gaming Central about getting Sonic Frontiers mods and I made it all the way to the end. I got HMM installed, but instead of starting up (Which is what it said it was trying to do) I get a Wine error (It said wineserver: using server-side synchronization and wine: RLIMIT_NICE is <= 20, unable to use setpriority safely). After these show up, it then proceeds to dump a bunch of text in the terminal that I don't understand (To be fair I didn't understand anything I was reading but still). I was able to instal it but it just won't load for some reason.

**Comment by thesupersonic16** [comment] 2023-03-22 03:19
Please use the issue #219 for getting/providing help with setting up HMM and its games on Linux.

I will now close this issue.

**Closed as completed by thesupersonic16** 2023-03-22 03:19 UTC
Labels: duplicate

**Comment by thesupersonic16** [comment] 2023-03-22 03:20
Also duplicate of #596
