### ISSUE TITLE
Sonic Generations not launching

### ISSUE THREAD

**Issue by epic-bruh-moment** [thesupersonic16/HedgeModManager#58] opened 2020-01-28 09:46 UTC
![image](https://user-images.githubusercontent.com/60384541/73252757-72f20000-41e5-11ea-8933-d94e959b90c6.png)

the game does not launch for me and gives me this error, I tried running Forces and SLW, which work perfectly for me

**Comment by Sajidur78** [comment] 2020-01-28 22:42
Looks like something is wrong with the C++ runtime, try re-installing the VC++ redistributables.
[Microsoft Visual C++ Redistributables 2019](https://aka.ms/vs/16/release/vc_redist.x86.exe)

**Comment by epic-bruh-moment** [comment] 2020-01-29 10:17
I did that, but still it's the same, weird part is the fact that forces and lost world work perfectly for me

**Comment by thesupersonic16** [comment] 2020-01-29 13:22
You can also try clean everything by closing HMM and deleting cpkredir.ini from the Sonic Generations folder and ModsDb.ini from the mods folder and then running HMM again and pressing Save & Play.

**Comment by epic-bruh-moment** [comment] 2020-01-31 04:38
> You can also try clean everything by closing HMM and deleting cpkredir.ini from the Sonic Generations folder and ModsDb.ini from the mods folder and then running HMM again and pressing Save & Play.

tried doing that, it worked and my mods loaded, but I can't close the issue yet, as when I loaded codes, the error happened again

**Comment by thesupersonic16** [comment] 2020-01-31 05:02
@Sajidur78 You think the issue is in GCL having issues loading the codes file?

**Comment by Sajidur78** [comment] 2020-01-31 08:10
That shouldn't cause an issue but maybe there's some invalid code/patch there that's making the runtime crash

**Comment by thesupersonic16** [comment] 2020-01-31 08:37
Does it work when there is no codes checked? if not, can you try deleting Codes.dat then press Play (Not Save & Play)?

**Comment by epic-bruh-moment** [comment] 2020-01-31 11:21
![image](https://user-images.githubusercontent.com/60384541/73535537-fdd53380-444d-11ea-8a1e-b2fea3391a4b.png)


> Does it work when there is no codes checked? if not, can you try deleting Codes.dat then press Play (Not Save & Play)?

I did all of it, and it works. anyway to make codes work?

**Comment by thesupersonic16** [comment] 2020-01-31 12:02
Since we know the issue is related to the codes, I would like to know if the issue on HMM or GCL. Can you enable **only** `Infinite Rings` then press Save and send me the Codes.dat file in a zip so I can check if its being written correctly.

**Comment by epic-bruh-moment** [comment] 2020-02-01 05:11
>Since we know the issue is related to the codes, I would like to know if the issue on HMM or GCL. Can you enable **only** `Infinite Rings` then press Save and send me the Codes.dat file in a zip so I can check if its being written correctly.

[Codes.zip](https://github.com/thesupersonic16/HedgeModManager/files/4142163/Codes.zip)
here, the code actually works, and launches the game

**Comment by epic-bruh-moment** [comment] 2020-02-20 09:51
> Since we know the issue is related to the codes, I would like to know if the issue on HMM or GCL. Can you enable **only** `Infinite Rings` then press Save and send me the Codes.dat file in a zip so I can check if its being written correctly.

so, I'm replying really late and I did a check, the unleashed stomp momentum code, is not letting me boot the game, the other codes work fine for me

**Comment by thesupersonic16** [comment] 2020-02-20 10:59
So just that one code?

**Comment by epic-bruh-moment** [comment] 2020-02-21 12:54
> So just that one code?

yes, I just got the latest release, it boots me to the game, but the moment I stomp, the game crashes without any message

**Comment by epic-bruh-moment** [comment] 2020-04-24 06:07
Stomp code still does not work

**Closed as completed** 2020-05-02 10:33 UTC
