### ISSUE TITLE
[Sonic Generations] 

### ISSUE THREAD

**Issue by pico1021** [thesupersonic16/HedgeModManager#132] opened 2020-08-21 02:06 UTC
[HMM_Snapshot_00082020220255.txt](https://github.com/thesupersonic16/HedgeModManager/files/5106373/HMM_Snapshot_00082020220255.txt)

HMM Info:
```
    Version: 7.2-5
    Args: 
    StartDir: T:\SteamLibrary\steamapps\common\Sonic Generations
    Process Level: User
    Game: Sonic Generations
    SteamGame: Sonic Generations
```

Exception:
```
    Type: InvalidOperationException
    Message: The calling thread cannot access this object because a different thread owns it.
    Source: WindowsBase
    Function: Void VerifyAccess()
    StackTrace: 
       at System.Windows.Threading.Dispatcher.VerifyAccess()
       at System.Windows.Application.CriticalShutdown(Int32 exitCode)
       at HedgeModManager.MainWindow.StartGame()
       at HedgeModManager.MainWindow.<<UI_SaveAndPlay_Click>b__27_0>d.MoveNext()
    InnerException: 
```

**Comment by thesupersonic16** [comment] 2020-08-21 02:37
Thanks for posting. Unfortunately this issue is also a duplicate of #130 which I have already fixed but have not yet released a build containing the fix. Since this is also a duplicate I will also be closing this issue. For the time being you can enable the option to keep HMM open in the settings.

**Closed as completed by thesupersonic16** 2020-08-21 02:37 UTC
