### ISSUE TITLE
HedgemodManager doesn't load any Sonic Forces mod or code

### ISSUE THREAD

**Issue by ThomasPoloBelgini** [thesupersonic16/HedgeModManager#470] opened 2022-09-19 02:44 UTC
so hedgemodmanager was working normally, until after a long time of use i started playing Sonic Generations using mods and HedgemodManager, and it was working, but when i came back after a long time without playing (Sonic Forces), I went to use it (hedgemodmanger), enabled the mods, the codes and went to play,
but when I started a level, the game was not modified, and the game didn't change anything, regardless of the mod or code that I enabled that I enabled, so I closed the game and enabled the option in the "Enable Bug Console" settings and started the game again, a black window appeared saying only, "[HE2ML] [INFO] Starting HE2Modloader v1.0.2...
" and nothing else, even with several or few mods enabled, and even so the game was not modified, it was the same, even with the mods and codes enabled, what do I do to solve this? because in other games like generations, it works usually.

(i used Google Translator to comment this)

**Comment by thesupersonic16** [comment] 2022-09-19 05:13
Are you using a legit Steam copy of Sonic Forces? There is a known bug that breaks pirated copies of Sonic Forces.

**Comment by ThomasPoloBelgini** [comment] 2022-09-19 16:18
no, I'm using a pirated version, but before, even using the pirated version, it worked fine, the mods and code loaded without any errors, until then it stopped working; but everything worked fine before

the strangest thing is that Sonic Generations is also pirated, and works normally

**Comment by thesupersonic16** [comment] 2022-09-19 16:27
The bug is related to how the Sonic Forces crack works which is very different from how the other Sonic games like Generations work. The cause of the issue was not intentional.

Unfortunately we do not provide support for pirated copies. You can try downgrade to FML on your own or buy a legit copy of the game which does often go on sale for 75% off.

I am sorry to say this, but because this is a case of piracy, I will be closing this issue.

**Closed as not planned by thesupersonic16** 2022-09-19 16:27 UTC
