### ISSUE TITLE
[SonicGenerations] 

### ISSUE THREAD

**Issue by xtremefunone** [thesupersonic16/HedgeModManager#421] opened 2022-06-03 03:51 UTC
HMM Info:
```
    Version: 7.7-0-80d6811
    Args: 
    StartDir: C:\Program Files (x86)\Steam\steamapps\common\Sonic Generations\
    Process Level: User
    Game: Sonic Generations
    GameInstall: Sonic Generations
    Update Status: Up To Date
```

Exception:
```
    Type: ArgumentException
    Message: Illegal characters in path.
    Source: mscorlib
    Function: Void CheckInvalidPathChars(System.String, Boolean)
    StackTrace: 
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.InternalGetDirectoryName(String path)
       at HedgeModManager.HedgeApp.FindAndSetLocalGame() in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 462
       at HedgeModManager.HedgeApp.Main(String[] args) in D:\a\HedgeModManager\HedgeModManager\HedgeModManager\HedgeApp.xaml.cs:line 202
    InnerException: 
```

**Comment by Sajidur78** [comment] 2022-06-03 04:00
Duplicate of #420

**Closed as completed by Sajidur78** 2022-06-03 04:00 UTC
